In [23]:
import os
import pandas as pd
import time
import numpy as np

In [24]:
filename = "fridge.csv"

In [25]:
def find_test_filename(test_dir, appliance, test_type) -> str:
    # Find test file name given a dataset name
    for filename in os.listdir(os.path.join(test_dir, appliance)):
        if test_type == 'train' and 'TRAIN' in filename.upper():
            test_filename = filename
            break
        elif test_type == 'uk' and 'UK' in filename.upper():
            test_filename = filename
            break
        elif test_type == 'redd' and 'REDD' in filename.upper():
            test_filename = filename
            break
        elif test_type == 'test' and 'TEST' in filename.upper() and 'TRAIN' not in filename.upper() and 'UK' not in filename.upper():
            test_filename = filename
            break
        elif test_type == 'val' and 'VALIDATION' in filename.upper():
            test_filename = filename
            break
    return test_filename

In [27]:
def load_dataset(file_name, crop=None):
    # Load CSV file and return mains power, appliance power and status
    df = pd.read_csv(file_name, nrows=crop)
    mains_power = np.array(df.iloc[:, 3], dtype=np.float32)
    appliance_power = np.array(df.iloc[:, 3], dtype=np.float32)
    activations = np.array(df.iloc[:, 5], dtype=np.float32)

    print(mains_power)
    print(appliance_power)
    print(activations)
    return mains_power, appliance_power, activations

load_dataset(filename)

[0.06 0.06 0.06 ... 0.57 0.56 0.56]
[0.06 0.06 0.06 ... 0.57 0.56 0.56]
[ 301.  301.  301. ... 3943. 3943. 3943.]


C:\Users\osama\AppData\Local\Temp\ipykernel_24156\4181002873.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, nrows=crop)


(array([0.06, 0.06, 0.06, ..., 0.57, 0.56, 0.56], dtype=float32),
 array([0.06, 0.06, 0.06, ..., 0.57, 0.56, 0.56], dtype=float32),
 array([ 301.,  301.,  301., ..., 3943., 3943., 3943.], dtype=float32))